FAN_Abbreviation = Аббревиатура
FAN_Common = Общие
FAN_CommonName = Общее название
FAN_CommonNames = Общие названия
FAN_Erase = Стереть
FAN_Iupac = IUPAC
FAN_IupacName = Название по IUPAC
FAN_IupacNames = Названия по IUPAC
FAN_Name = Название
FAN_Names = Названия
